// Generated by Wrangler on Tue Jul 30 2024 23:35:06 GMT+0800 (中国标准时间)
// by running `wrangler types`

interface Env {
	AZ_TOKENS: KVNamespace;
	CLIENT_ID: string;
	CLIENT_SECRET: string;
	DB: D1Database;
}
